config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:'pages#home'
  resources :listings
  post 'payments/webhook', to: 'payments#webhook'
  get 'payments/success', to: 'pages#payment_success'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :category
  belongs_to :engine
  belongs_to :user
  enum condition: {damaged: 0, used: 1, good: 2, excellent: 3}
  enum color: {beige: 0, black: 1, blue: 2, bronze: 3, brown: 4, gold: 5, green: 6, grey: 7, magenta: 8, maroon: 9, burgundy: 10, orange: 11, pink: 12, purple: 13, red: 14, silver: 15, white: 16, yellow: 17}
  enum transmission: {manual: 0, automatic: 1}
  enum starter: {pedal: 0, electric: 1}
  has_many :listing_features, dependent: :destroy
  has_many :features, through: :listing_features
  accepts_nested_attributes_for :listing_features
  has_one_attached :picture

  before_save :remove_whitespace
  before_validation :change_price_to_cents, if: :price_changed?

  private

  def remove_whitespace # removing whitespace from name and description fields 
    self.name = self.name.strip 
    self.description = self.description.strip
  end

  def change_price_to_cents # changing pricing for the listing to cents
    self.price = (self.price * 100).round
  end

  def change_from_booked_to_available #changing a booked status to available
    if self.available == false
      change_available_status = self
      change_available_status.available == true
      change_available_status.save
      return change_available_status
    end
  end
  end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  load_and_authorize_resource 
  before_action :set_listing, only: %i[ show ]
 # before_action :set_user_listing, only: [:update, :edit, :destroy]
  before_action :set_vars_form, only: [:new, :edit]

  # GET /listings or /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1 or /listings/1.json
  def show
    stripe_session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      client_reference_id: current_user ? current_user.id : nil,
      customer_email: current_user ? current_user.email : nil,
      line_items: [{
        amount: @listing.price,
        name: @listing.name,
        description: @listing.description,
        currency: 'aud', 
        quantity:1
      }],
      payment_intent_data: {
        metadata: {
          listing_id: @listing.id,
          user_id: current_user ? current_user.id : nil
        }
      },
      success_url: "#{root_url}payments/success?listingId=#{@listing.id}",
      cancel_url: "#{root_url}listings"
    )
    @session_id = stripe_session.id
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings or /listings.json
  def create
    @listing = current_user.listings.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    def set_user_listing
      @listing = current_user.listings.find_by_id(params[:id])
    #  if @listing == nil
     #   flash[:alert] = "You don't have persmission to do that"
     #   redirect_to listings_path
    #  end
    end


    def set_vars_form # setting up main 
      @categories = Category.all
      @conditions = Listing.conditions.keys
      @engines = Engine.all
      @features = Feature.all
      @colors = Listing.colors.keys
      @transmissions = Listing.transmissions.keys
      @starters = Listing.starters.keys
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:name, :picture, :price, :category_id, :engine_id, :description, :condition, :odometer, :color, :transmission, :starter, :insurance, :images, :available, feature_ids: [])
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
    def render_stripe_button(current_user)
        if current_user
            button = "<button data-stripe=\"payment\" class='btn btn-primary p-3'> Book: $<%=@listing.price%></button>"
        else
            button ="<button class='btn btn-primary' disabled> Login To Book</button>"
        end
        return button.html_safe
    end
    def convert_price_to_dollars(price)
        number_with_precision price/100, precision: 2
    end

end

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :category_id, class: "form-label" %>
    <%= form.select :category_id, categories.map {|cat| [cat.name, cat.id]}, class: "form-select" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :engine_id, class: "form-label" %>
    <%= form.select :engine_id, engines.map {|engine| [engine.name, engine.id]}, class: "form-select" %>
  </div>

 
<h6 class='mb-3'>Condition</h6>
 <div class="form-check form-check-line mb-3">
  <%conditions.each do |option|%>
    <%= form.label :condition, option.capitalize, class: "form-label" %>
    <%= form.radio_button :condition, option, class: "mr-2" %>
    <%end%>
  </div>

  <h6 class='mb-3'> Features </h6>
  <div class= 'form-check mb-3'>
    <%= form.collection_check_boxes :feature_ids, features, :id, :name do |b| %>
    <%=b.label(class: 'form-check-label') %>
    <%=b.check_box(class: 'form-check-line mr-2')%>
    <% end %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :odometer, class: "form-label" %>
    <%= form.number_field :odometer %><p> kms </p>
  </div>

<div class="form-group mb-3">
    <%= form.label :color, class: "form-label" %>
    <%= form.select :color, colors %>
</div>

<div class="form-group mb-3">
    <%= form.label :transmission, class: "form-label" %>
    <%= form.select :transmission, transmissions %>
</div>

<div class="form-group mb-3">
    <%= form.label :starter, class: "form-label" %>
    <%= form.select :starter, starters %>
</div>

  <div class="form-check mb-3">
    <%= form.label :insurance, class: "form-label" %>
    <%= form.check_box :insurance %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :picture, class: "form-label" %>
    <%= form.file_field :picture, accept: 'image/png, image/jpg, image/jpeg', class: "form-control-file" %>
    <small class='form-text text-muted'> PNG, JPG, or JPEG only </small>
  </div>

  <div class="form-group mb-3">
    <%= form.label :available, class: "form-label" %>
    <%= form.check_box :available %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :price, class: "form-label" %>
    <%= form.number_field :price, class: "form-control" %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing, categories: @categories, conditions: @conditions, engines: @engines, colors: @colors, transmissions: @transmissions, starters: @starters, features: @features %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<h1 class='hero-title text-center'> Listings </h1>
<div class='container'>
  <div class='row row-cols-sm-1 row-cols-md-2 row-cols-lg-4'>
    <%@listings.each do |listing|%>
      <div class='col mb-4'>
        <div class='card border-dark h-100'>
            <% if listing.picture.attached?%>
              <%=image_tag listing.picture, class: "thumbnail card-img top"%>
            <% else %>
              <%=image_tag "vespa-orange.jpg", alt: "orange Vespa scooter", class: "thumbnail card-image top"%>
            <%end%>          
            <div class='card-body'>
            <h5><%=listing.name%></h5>
            <h6 class='card-subtitle my-2 text-muted'>Added <%=time_ago_in_words(listing.created_at)%> ago </h6>
            <p class='card-text text-secondary text-truncate'><%=listing.description%></p>
              <%if listing.available == true%> 
                <h6 class='my-2 text-success'>Available for Booking</h6>
              <% else listing.available == false%> 
                <h6 class='my-2 text-muted'><em>Booked</em></h6>
              <%end%>
            <div class='d-flex justify-content-between'>
              <%= link_to "See More", listing_path(listing.id), class: "btn btn-outline-primary"%>
              <h5> $ <%=convert_price_to_dollars(listing.price)%> </h5>
            </div>
          </div>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing, categories: @categories, conditions: @conditions, engines: @engines, colors: @colors, transmissions: @transmissions, starters: @starters, features: @features %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<div class='container d-flex flex-column flex-md-row px-2 my-2 my-md-5'>
  <div class='col-12 col-md-7 col-lg-8 p-0 pr-md-3'>
    <div class='col-12 p-0 main-preview mb-4'>
      <% if @listing.picture.attached?%>
        <%=image_tag @listing.picture, class: "thumbnail card-img top"%>
      <% else %>
        <%=image_tag "vespa-orange.jpg", alt: "orange Vespa scooter", class: "thumbnail card-image top"%>
      <%end%>
    </div>
  </div>
    <div class='col-lg-4 p-0 mx-2 d-md-block'>
      <h1 class='mb-sm-2 mb-md-5'><%=@listing.name%></h1>

      <p class='blockquote mt-2'><%=@listing.description%></p>
      <h4 class='text-muted'> Condition: <%=@listing.condition.capitalize%></h4>
      <h4 class='text-muted'> Odometer: <%=@listing.odometer%> kms</h4>
      <h4 class='text-muted'> Color: <%=@listing.color%></h4>     
        <%if @listing.insurance == true%> 
            <h4 class='text-muted'> Insurance: Insured </h4>
        <% else @listing.insurance == false%> 
            <h4 class='text-muted'> Insurance: Uninsured </h4>
        <% end %>

      <h4 class='text-muted'> Model: <%=@listing.category.name%></h4>
      <h4 class='text-muted'> Engine: <%=@listing.engine.name%></h4>
      <h4 class='text-muted'> Transmission: <%=@listing.transmission%></h4>
      <h4 class='text-muted'> Kickstarter: <%=@listing.starter%></h4>

      <%@listing.features.each do |feature|%>
        <span class='badge badge-pill badge-info'><%=feature.name%></span>
        <%end%>

      <%if current_user && @listing.available == true%> 
        <button data-stripe="payment" class='btn btn-primary p-3'> Book: $<%=convert_price_to_dollars(@listing.price)%></button> 
      <%elsif @listing.available == false%> 
        <button class='btn btn-secondary' disabled> BOOKED </button>
      <% else%>
        <%=button_to "Login to buy", new_user_session_path, class: "btn btn-info" %> 
      <%end%>
    </div>
  </div>
</div>

<div class='container'>
  <div class ='d-flex justify-content-evenly'>
    <%=link_to "Edit", edit_listing_path(@listing.id), class: "btn btn-warning mr-3" if can? :update, @listing %>
    <%=link_to "Delete", @listing, method: :delete, data: {confirm: "Are you sure?"} , class: "btn btn-danger mr-3" if can? :destroy, @listing%>
  </div>
</div>

<script src="https://js.stripe.com/v3/"></script>
<script>
    document.querySelector("[data-stripe='payment']")
    .addEventListener("click", () => {
        const stripe = Stripe(
          "<%=Rails.application.credentials.dig(:stripe, :public_key)%>"
        );
        stripe.redirectToCheckout({
          sessionId: "<%= @session_id%>"
        });
    });
</script>