config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:'pages#home'
  resources :listings
  post 'payments/webhook', to: 'payments#webhook'
  get 'payments/success', to: 'pages#payment_success'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light d-flex px-2">
    <a class="navbar-brand" href="#">
    <%= image_tag "favicon-32x32.png"%>
    Vespa Sharing Club
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse mr-autod-flex justify-content-between" id="navbarSupportedContent">
    <ul class="navbar-nav mr-5-lg">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link"%>
      </li>
      <li class="nav-item active">
        <%= link_to "Find a Vespa", listings_path, class: "nav-link"%>
      </li>
      <li class="nav-item active">
        <%= link_to "Share a Vespa", new_listing_path, class: "nav-link"%>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <ul class="nav-item px-2">
        <% if user_signed_in?%>
          <p class="text-sm-left font-italic"> Welcome <%= current_user.email%></p>
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
            <%= link_to "Log Out", destroy_user_session_path, method: :delete if user_signed_in?%>
          </button>
        <%else%>
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
            <%=link_to "Log In", new_user_session_path%>
          </button>
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
            <%=link_to "Sign Up", new_user_registration_path%>
          </button>
        <%end%>     
      </ul>
    </form>
  </div>
</nav>